import { Inter } from "next/font/google";
import "./globals.css";

// ** Contexts
import { SettingsProvider } from './config/context/settingsContext'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SettingsProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </SettingsProvider>
  );
}
