services:
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: node:latest
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    command: sh -c "npm install && npm run test && npm run startdev"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: ankane/pgvector
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pg_node_js
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    networks:
       - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge